### ISSUE TITLE
minical extension - produces error

### ISSUE THREAD

**Issue by miconx** [DHTMLX/scheduler#12]
if i use the minical extension, i get  a javascript error when i click on the minical icon
the error: "ReferenceError: getOffset is not defined"

**Comment by AlexKlimenkov** [comment]
Hi,
please provide some kind of demo, the extension seems to work correctly in our samples - 
http://docs.dhtmlx.com/scheduler/snippet/67d7a317

**Comment by miconx** [comment]
i think the error is only reproducable within a meteor environment - the dhtmlx-snippet server ist not running meteor...
i´m sorry but i´m not able to provide an example on a public server.
but this is what i´ve been doing: 
1. created a  new meteor project
2. downloaded & added dhtmlx scheduler + scheduler-data packages with meteor add PACKAGENAME
3. activate "... pakageSourcesFolder + "ext/dhtmlxscheduler_minical.js", ..." to api.addFiles call in package.js 
4. added the minical div ( " <div class="dhx_minical_icon" id="dhx_minical_icon">&nbsp;</div> ") to my scheduler template 
5. start the meteor app --> click on minical icon produces the error ...

INFO:
if i add an extra file to the meteor project wherein i copy paste all getOffset* functions from the main dhtmlxscheduler.js file everything works....

**Comment by nabiltntn** [comment]
i have the problem in Meteor. Since the package exports only the scheduler object to the external world, function like getOffset won't be visible to extensions like minical.

I am not sure if it's possible to export also all the 'private' functions that are used by extensions.

**Comment by AlexKlimenkov** [comment]
Should be fixed https://github.com/DHTMLX/meteor-scheduler/pull/12
