### ISSUE TITLE
How to hide deleted event while scheduler loading

### ISSUE THREAD

**Issue by gagankumar971** [DHTMLX/scheduler#16]
Hi,

While loading scheduler events , I want to hide some of the events if rec_type=="none".

scheduler.parse([{"text":"Task1","id":"1458040356684","start_date":"2016-03-15 01:10:00.0","end_date":"2016-04-14 00:00:00.0","rec_type":"day_1___#","event_pid":"","event_length":"2587800","section_id":"4","event_status":null},{"text":"Task1","id":"1458103543817","start_date":"2016-03-16 01:10:00.0","end_date":"2016-04-15 00:00:00.0","rec_type":"none","event_pid":"1458040356684","event_length":"2587800","section_id":"4","event_status":"delete"}],"json");

how can I do this. I have used the filter as follows but it does not work for all events.

scheduler.filter_day = function(id, event){
console.log('inside filter_day'+id + (event.rec_type=="none"));

if(event.rec_type=="none")
{
//return false; // event will be filtered (not rendered)
}

return true; // event will be rendered

};

Please help.

**Comment by AlexKlimenkov** [comment]
continued here
http://forum.dhtmlx.com/viewtopic.php?f=6&t=50454
