### ISSUE TITLE
Scheduler- can we have webjar or npm for the javascript UI library

### ISSUE THREAD

**Issue by gagankumar971** [DHTMLX/scheduler#17]
Hi,
I am using dhtmlx-scheduler, It provides descent UI component with javascript UI library.
can we have webjar or npm for  javascript UI library.

**Comment by kanderson450** [comment]
+1

**Comment by AlexKlimenkov** [comment]
Hi,
we'll publish npm package soon, not sure about webjar.

**Comment by AlexKlimenkov** [comment]
Hi,
here is npm package https://www.npmjs.com/package/dhtmlx-scheduler , sorry for a long wait
