### ISSUE TITLE
Scheduler - Timeline onDragEnd

### ISSUE THREAD

**Issue by Seabizkit** [DHTMLX/scheduler#2]
Has no access to the event? This is on time-line

**Comment by AlexKlimenkov** [comment]
The event seems working as expected
https://docs.dhtmlx.com/scheduler/api__scheduler_oneventdrag_event.html
code:
```
scheduler.attachEvent("onEventDrag", function (id, mode, e){
    dhtmlx.message("onEventDrag");
    console.log(scheduler.getEvent(id), "scheduler event");
    console.log(e, "browser event");
    return true;
});
```
and a live demo: http://snippet.dhtmlx.com/3329e1829
