### ISSUE TITLE
Scheduler rendering issue - Missing calendar boundary

### ISSUE THREAD

**Issue by themoonraker13** [DHTMLX/scheduler#24]
I've used the dhtmlx scheduler v 4.3.1 in my web application. I've found a UI related issue with the scheduler calendar wherein the **left boundary/border (vertical bar) of the calendar is clearly missing or not rendering**.

![untitled](https://cloud.githubusercontent.com/assets/8231852/17247498/47030288-55b1-11e6-8aaa-c5206e80aa7c.png)

I've reduced the size of scheduler div to occupy the center portion of the page as seen in the attached screenshot unlike the online demo of scheduler where the scheduler covers the entire page making the outer-edges invisible.

**Comment by AlexKlimenkov** [comment]
I think it's intended, or at least absence of these borders is consistent between all skins of dhtmlxScheduler.
Scheduler is expected to receive borders from the outer container.
Or you can add a border to the div where scheduler is initialized, e.g.:
```
#scheduler_here{
   border: 1px solid #cecece;
}
```
