### ISSUE TITLE
Scheduler repeating events - toggle problem

### ISSUE THREAD

**Issue by bmatasar** [DHTMLX/scheduler#25]
**Steps to reproduce the issue**
1. Create a repeating event
2. Modify an occurrence of the series and click Save
3. Edit again the modified occurrence. Note the toggle button for "Repeat events" is disabled. Click on it once, then save.

It will wrongly create a series out of the modified occurrence, with event_pid still pointing at the first series.

**Resolution**
This is caused by a bug in dhtmlxscheduler_recurring.js, method scheduler._toggle_block:
Even if `cont.blocked`, `cont.open` is toggled.

**Comment by AlexKlimenkov** [comment]
Hi,
we've reproduced the issue and added your fix to the main repo. sorry for a long inactivity.
I'll close the related pull request, the repository will be updated with the next minor update of the scheduler (early-mid March 2018)
