### ISSUE TITLE
Scheduler - Timeline onDragEnd

### ISSUE THREAD

**Issue by Seabizkit** [DHTMLX/scheduler#3]
the on-click event is fired... This is on Time-line

**Comment by AlexKlimenkov** [comment]
doesn't seems to happen in the latest version
https://docs.dhtmlx.com/scheduler/api__scheduler_oneventdrag_event.html
code:
```
scheduler.attachEvent("onEventDrag", function (id, mode, e){
    dhtmlx.message("onEventDrag");
    console.log(scheduler.getEvent(id), "scheduler event");
    console.log(e, "browser event");
    return true;
});
```
and a live demo: http://snippet.dhtmlx.com/3329e1829
