### ISSUE TITLE
Scheduler for mobile devices

### ISSUE THREAD

**Issue by janmottl** [DHTMLX/scheduler#33]
I am very satisfied with Scheduler and I would like to use it on mobile device too. Scheduler for mobile devices is pretty old (4 years). Is it maintained or is it dead product? What do you suggest for mobile devices? Thanks

**Comment by AlexKlimenkov** [comment]
Hi,
dhtmlxScheduler Mobile is not in the active development anymore, although we maintain it within a customer support system.
For new projects, if you're looking for something similar, I'd suggest checking out webix mobile scheduler https://webix.com/scheduler/

**Comment by janmottl** [comment]
It looks cool. Thanks.
