### ISSUE TITLE
events added by double click always end up at current time instead of clicked time. source is issue in addEventNow

### ISSUE THREAD

**Issue by saltomodules** [DHTMLX/scheduler#35]
`scheduler.addEventNow()` contains this if test:

https://github.com/DHTMLX/scheduler/blob/1ff13c772208e2d945499a27e6c54a36ef543245/codebase/sources/dhtmlxscheduler.js#L2723

~In newer browsers this test also passes when the `start` argument for `addEventNow()` contains just a Date object. This is because `constructor.toString()` no longer just returns the signature but the entire function body. For Date() this happens to contain an occurence of 'object', which makes the if test pass.~

 EDIT: upon further investigation it is not newer browsers which alter the toString() return value but the `core-js` module we use in our (meteor) project, which seems to override the toString method of functions. See reply for more details.

When this happens just a Date object gets assigned to `base` which now has no `start_date` field. 

This in turn results in `start` always being assigned the output of `_currentDate()` on line 2729, even though we did have a start argument:
https://github.com/DHTMLX/scheduler/blob/1ff13c772208e2d945499a27e6c54a36ef543245/codebase/sources/dhtmlxscheduler.js#L2729

This results in events added by double click always ending up at the current time instead of the clicked time.

We ran into the issue because in the build in double click handler `addEventNow()` gets called with just a Date object:
https://github.com/DHTMLX/scheduler/blob/1ff13c772208e2d945499a27e6c54a36ef543245/codebase/sources/dhtmlxscheduler.js#L2770

Perhaps a solution could be calling `addEventNow()` with a wrapper object argument (as per the documentation) instead of a raw Date object.

**Comment by saltomodules** [comment]
Upon further investigation with the debugger in chrome it is not 'newer browsers' which alter the toString() return value but the `core-js` module we use in our (meteor) project, which seems to override the toString method of functions:

https://github.com/zloirock/core-js/blob/ab8ad81ed4a5fd8c1009a336113eec61f04eaa82/modules/_redefine.js#L29

So this doesn't strictly seem to be an issue with dhtmlx scheduler, but perhaps you still find it a good idea to alter the if test in question to permanently rule out running into this type of issue

**Comment by AlexKlimenkov** [comment]
Hi,
sorry for a long wait.
We'll change the test for a date object there to something close to these lines:

```
function isDate(obj){
	if (obj && typeof obj == "object") {
		//  object looks close enough to js Date, 
		//  not likely there is a legit use case for a false-positive error
		return !!(obj.getFullYear && obj.getMonth && obj.getDate);
	} else {
		return false;
	}
};

scheduler.addEventNow=function(start,end,e){
   var base = {};
   if (start && !isDate(start)){
      ...
   }
```
It should resolve the issue you have, and also will make that line a bit less cryptic.
The repository will be updated when we publish the next update, probably in February-March 2018
