### ISSUE TITLE
dhtmlx-scheduler

### ISSUE THREAD

**Issue by chenwei0104** [DHTMLX/scheduler#36]
I wanna use timeline mode in scheduler but i can't find files which used in the samples.
codebase/ext/dhtmlxscheduler_timeline.js and codebase/ext/dhtmlxscheduler_treetimeline.js

**Comment by AlexKlimenkov** [comment]
Hi,
the timeline and tree timeline is not included in the Standard version of the scheduler (the one which is published here).
If you check here - https://docs.dhtmlx.com/scheduler/views.html - everything that is marked with 'PRO' badge is available in the Professional edition only, i.e. Commercial, Enterprise and Evaluation versions
