### ISSUE TITLE
Scheduler - Timeline Image/icon in event 

### ISSUE THREAD

**Issue by Seabizkit** [DHTMLX/scheduler#4]
scheduler.templates.event_class

and setting background overrides the background image

would be nice if there was a default way of setting an icon for an event eg a lock... to illiterate that it cannot be moved.

**Comment by AlexKlimenkov** [comment]
Icons and any other html content can be injected into event elements using event_text and event_bar_text templates
https://docs.dhtmlx.com/scheduler/api__scheduler_event_bar_text_template.html

```
scheduler.templates.event_bar_text = function(start, end, event){
  var img = "<img  src='url' />";
  return event.text + img;    
};

```
demo: http://snippet.dhtmlx.com/bf3a1b059
