### ISSUE TITLE
Make it responsive

### ISSUE THREAD

**Issue by akvaliya** [DHTMLX/scheduler#43]
Looks really weird in mobile devices

![](https://content.screencast.com/users/Akvaliya/folders/Jing/media/78e974d1-d57b-48fe-9089-9d1d9873a2ee/2019-08-08_1959.png)

Any plan to provide responsive support?

**Comment by zipzit** [comment]
Me, too.  I know exactly what I want,. but can't quite get there from here... In the meantime..

/* dhtml scheduling CSS hacks... */
#meeting-schedule .dhx_agenda_area .dhx_agenda_line span {
    display: contents;
}

/* https://forum.dhtmlx.com/t/responsive-design/66934/2 */
@media screen and (max-width: 600px) {
    .dhx_cal_navline{height:100px!important}
  	.dhx_cal_date{margin-top:50px}
  }

**Comment by AlexKlimenkov** [comment]
Hi!

We've just published an update which should address some issues with responsiveness

Related docs:
http://localhost:500/scheduler-docs-github/touch_support.html

And here is a demo:
https://docs.dhtmlx.com/scheduler/samples/01_initialization_loading/13_touch_ui.html
