### ISSUE TITLE
Scheduler - Timeline Prevent dragging between sections - Feature request

### ISSUE THREAD

**Issue by Seabizkit** [DHTMLX/scheduler#5]
Hi

Could someone tell me what is the best way to prevent and event from betting able to be dragged into another section (y axis).

i.e. I do not want a user to be able to drag "John" events into "Pieter" Events...

But i do want "John" to be able to move the times of his events via dragging.

Thanks

**Comment by AlexKlimenkov** [comment]
It's usually done via onBeforeEventChanged event, it's fired on mouse up at the end of dnd and allows canceling operation:
https://docs.dhtmlx.com/scheduler/api__scheduler_onbeforeeventchanged_event.html
