### ISSUE TITLE
Calculate cover height w/lightbox

### ISSUE THREAD

**Issue by joshuaungheanu** [DHTMLX/scheduler#53]
Set cover height doesn’t set the variable thats defined in the function, thus not calculating the correct height with the lightbox. This issue did not exist in V5.0

**Issue**
dhtmlx Scheduler Version - `5.3.6`
Located - `dhtmlxscheduler.js file`
Line - `7718`

![Screen Shot 2020-04-16 at 7 29 56 PM](https://user-images.githubusercontent.com/7441927/79525823-ae4be000-8018-11ea-93cc-38edd4b3ed81.png)

**Comment by AlexKlimenkov** [comment]
Hi!
the issue should be fixed in v5.3.8 https://github.com/DHTMLX/scheduler/commit/95aa43450d93d1ce8ab870f62088e0dae2af6fb9
