### ISSUE TITLE
Events not showing for Safari Browser

### ISSUE THREAD

**Issue by johnson935** [DHTMLX/scheduler#54]
I've implemented a new scheduler with a mongo db database however when I try to use it in safari the events do not show up. However works fine in the other browsers

**Comment by MaksimLakatkou** [comment]
> I've implemented a new scheduler with a mongo db database however when I try to use it in safari the events do not show up. However works fine in the other browsers

Hello johnson935,
Sorry, but I can't reproduce the issue. I checked the loading and display of events in safari and everything seems to work. Perhaps some details are needed to reproduce, or the issue has already been fixed at the moment.
If you or anyone else still faces this issue, please send us code examples, screencasts, access to the demo, details to reproduce the issue.
