### ISSUE TITLE
OT: opening the DHTMLX code on GitHub?

### ISSUE THREAD

**Issue by dandv** [DHTMLX/scheduler#7]
Any plan to release the DHTMLX source code on GitHub?

Kendo is at https://github.com/telerik/kendo-ui-core

Webix is at https://github.com/webix-hub/tracker

**Comment by psema4** [comment]
Non-minified javascript sources would be most welcome.  Trying to debug a [tooltips](https://github.com/DHTMLX/scheduler/blob/master/codebase/ext/dhtmlxscheduler_tooltip.js) issue (where the tooltips are being positioned incorrectly - much like [this discussion](https://disqus.com/home/discussion/schedulernet/common_templates/#comment-819900580) - after changing between months in months view). Unfortunately, reading the optimized & minified source is... not much fun.

**Comment by AlexKlimenkov** [comment]
You can find non-minified sources in **/codebase/source** folder of a repo and also in a scheduler package. An Evaluation package don't have this, but all other editions comes with a readable source codes
https://github.com/DHTMLX/scheduler/tree/master/codebase/sources

**Comment by psema4** [comment]
Thanks @AlexKlimenkov, much appreciated!
