### ISSUE TITLE
Update to version 7.0.1 broke the example Code on the blog

### ISSUE THREAD

**Issue by sschausten** [DHTMLX/scheduler#72]
Hi, 

the update to version 7.0.1 with the changes to dhtmlxscheduler_material.css and codebase/dhtmlxscheduler.css broke the example code from the blog at https://dhtmlx.com/blog/use-dhtmlx-scheduler-vue-js-framework-demo/ 

The example code still tries to load the material.css file that no longer exists.

kind regards

**Comment by AlexKlimenkov** [comment]
Thanks! We've updated github demo and the tutorial will be updated in a few minutes
